### ISSUE TITLE
Changes "sound levels" by itself?

### ISSUE THREAD

**Issue by MPeti1** [therealahrion/Audio-Modification-Library#3]
I've reinstalled whole Magisk because i had some problems related to AML, but i'll write about it in the right place if i encounter it again.
I noticed the sound "quality" is changed after installing just AML (other installed modules are just

- ADB & Fastboot executables by osm0sis
- Busybox by osm0sis )

I mean it seems like if i increase the volume of the higher pitch sounds in some equalizer, such as Viper or Dolby Atmos, but i have no EQ at that moment installed.

OFF: Is this a right place for bug reports? I ask it because i don't see any other bug reports here, even not in the closed category.

**Comment by Zackptg5** [comment]
AML is just a framework that audio mods can use so AML in itself doesn't contain anything other than the audio config/policy/mixer files and a boot script that sets sepolicy and keeps track of all modules that use AML. 
So AML itself wouldn't cause this problem but a mod that uses it could so I'd post this in whatever mod you were using that causes this problem
