### ISSUE TITLE
Script magisk hide props config does not work when audiomodification library module is active

### ISSUE THREAD

**Issue by kot6230** [therealahrion/Audio-Modification-Library#4]
![Screenshot_2020-08-17-22-06-14-632_com termux](https://user-images.githubusercontent.com/60502974/90454426-e3b62680-e0fb-11ea-9ff4-371bb01e04c6.jpg)

**Comment by Zackptg5** [comment]
Got the wrong repo, this is the old aml. Current aml (and one in magisk repo) has a support thread for it here: https://forum.xda-developers.com/apps/magisk/mod-audio-modification-library-t3745466
